-- 모든 환자에 대해 총내원일수
SELECT PS.PERSON_ID, VO.VISIT_DAY AS 내원일수
  FROM PERSON PS	--모든 환자에 대한 조회
  LEFT OUTER JOIN (SELECT PERSON_ID, 
				     	  SUM(VISIT_END_DATE - VISIT_START_DATE+1) AS VISIT_DAY --환자별 내원일수의 합
				     FROM VISIT_OCCURRENCE
				    WHERE VISIT_CONCEPT_ID = '9201'
				    GROUP BY PERSON_ID) VO
    ON PS.PERSON_ID = VO.PERSON_ID


-- 총 내원일수의 최대값
SELECT MAX(VO.VISIT_DAY) --최대내원일수
 FROM (SELECT PERSON_ID, 
			  SUM(VISIT_END_DATE - VISIT_START_DATE+1) AS VISIT_DAY
		 FROM VISIT_OCCURRENCE
		WHERE VISIT_CONCEPT_ID = '9201'
		GROUP BY PERSON_ID) VO

--총 내원일수 최대값을 가지는 환자수
SELECT COUNT(*) AS 환자수 
  FROM (SELECT PERSON_ID, SUM(VISIT_END_DATE - VISIT_START_DATE+1) AS VISIT_DAY
		 FROM VISIT_OCCURRENCE
		WHERE VISIT_CONCEPT_ID = '9201'
		GROUP BY PERSON_ID ) PS
 WHERE PS.VISIT_DAY = (SELECT MAX(VO.VISIT_DAY) --내원일수가 최대값과 같은 환자수
					     FROM (SELECT PERSON_ID, 
							          SUM(VISIT_END_DATE - VISIT_START_DATE+1) AS VISIT_DAY
								 FROM VISIT_OCCURRENCE
								WHERE VISIT_CONCEPT_ID = '9201'
						    	GROUP BY PERSON_ID) VO)
	