SELECT DISTINCT CONCEPT_NAME
  FROM CONDITION_OCCURRENCE CO
  JOIN CONCEPT CC
    ON CO.CONDITION_CONCEPT_ID = CC.CONCEPT_ID
 WHERE LOWER(CC.CONCEPT_NAME) LIKE '%heart%'  --heart 포함
   AND LOWER(SUBSTRING(CONCEPT_NAME,1,1)) IN ('a','b','c','d','e') --a,b,c,d,e 포함
 
