SELECT DRUG_CONCEPT_ID, 
	   MIN(DRUG_EXPOSURE_START_DATE) AS START_DATE,  --처음 시작일
	   MAX(DRUG_EXPOSURE_END_DATE) AS END_DATE,		 --마지막 종료일
	   MAX(DRUG_EXPOSURE_END_DATE) - MIN(DRUG_EXPOSURE_START_DATE) +1 AS 복용일 
  FROM DRUG_EXPOSURE
 WHERE PERSON_ID = '1891866'
 GROUP BY DRUG_CONCEPT_ID
 ORDER BY MAX(DRUG_EXPOSURE_END_DATE) - MIN(DRUG_EXPOSURE_START_DATE) +1 DESC
 